#!/bin/bash
### BEGIN INIT INFO
# Provides: suricata
# Required-Start: $local_fs $remote_fs $network $named $syslog $time
# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop suricata
# Description: Suricata is a powerful open-source Intrusion Detection System.
### END INIT INFO

#The location of the suricata binary
SURICATAD=/usr/local/bin/suricata
#Command line execution options for suricata
OPTIONS="-D -c /usr/local/etc/suricata/suricata.yaml --af-packet"
do_start()
{
    echo "Starting Suricata" 
    /sbin/ifconfig suricata_iface1 up -arp -multicast promisc
    /sbin/ifconfig suricata_iface2 up -arp -multicast promisc
    $SURICATAD $OPTIONS
	if [ $? -eq 0 ]; then
		echo "Suricata successfully started."
		logger "Suricata Started!"
	else
		echo "Suricata failed to start!"
	fi
    return 0
}

do_status()
{
	pidof suricata
	if [ $? -eq 0 ]; then		
		echo "Suricata is running with a pid of `pidof suricata`"
	else
		echo "Suricata is not running."
	fi
}

do_stop()
{
    echo "Stopping Suricata"
    kill $(pidof suricata) 2> /dev/null
	if [ $? -eq 0 ]; then
		echo "Suricata successfully killed."
		logger "Killed Suricata."
	else
		echo "Suricata could not be killed! (Permissions? Already dead?)"
	fi
    return 0
}

case "$1" in
 start)
    do_start
    ;;
 stop)
    do_stop
    ;;
 restart)
    do_stop
    do_start
    ;;
 status)
	do_status
	;;
 *)
    echo "Usage: suricatad {start|stop|restart|status}" >&2
    exit 3
    ;;
esac
exit 0